version: '3'
services:
    demo_server:
        image: wadjetz/files-store-server
        environment:
            SECRET_KEY: secret
            DATABASE_URL: postgres://filesstore:filesstore@demo_database/filesstore
            LOCAL_STORAGE_PATH: /upload
            ASSETS: /files-store/assets
            RUST_LOG: "files-store=debug,actix_web=info"
            POSTGRES_PASSWORD: filesstore
            POSTGRES_USER: filesstore
            POSTGRES_DB: filesstore
        ports:
            - 4200:4200
        volumes:
            - .data/demo/upload:/upload
        depends_on:
            - demo_database

    demo_database:
        image: postgres:13.0-alpine
        environment:
            POSTGRES_PASSWORD: filesstore
            POSTGRES_USER: filesstore
            POSTGRES_DB: filesstore
        volumes:
            - .data/postgresql/data:/var/lib/postgresql/data
